/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Finestra.java
 *
 * Created on 15-nov-2011, 14:06:29
 */
package ascensor;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author joan
 */
public class Finestra extends javax.swing.JFrame {
    
    private int numPisos = 10;
    private Ascensor ascensor;
    private Dimension tamanyFinestra;
    private final int TIMER_DELAY = 5;
    private int tamanyPis = 70;
    private JPanel[] pisos = new JPanel[numPisos];
    
    public void creaPisos(){
        for (int i = 0; i < numPisos; i++){
            pisos[i] = new JPanel();
            pisos[i].setBounds(this.PanelPrincipal.getLocation().x,
                    this.PanelPrincipal.getHeight() - tamanyPis - 20 - (i * tamanyPis),
                    300,
                    tamanyPis);
            pisos[i].setBorder(BorderFactory.createLineBorder(Color.black));
            pisos[i].setBackground(null);
            pisos[i].setLayout(new GridLayout());
            pisos[i].add(new JButton("Pujar"));
            pisos[i].add(new JButton("Baixar"));
            this.PanelPrincipal.add(pisos[i], BorderLayout.EAST);
        }
    }
    
 

    /** Creates new form Finestra */
    public Finestra(){
        initComponents();
        this.setTitle("Ascensor");
        this.tamanyFinestra = new Dimension(400, numPisos * tamanyPis);
        this.setPreferredSize(tamanyFinestra);
        this.PanelPrincipal.setSize(tamanyFinestra);        
        this.ascensor = new Ascensor(numPisos);  //cream un nou ascensor
        PanelPrincipal.add(ascensor);
        ascensor.setBackground(Color.RED);
        ascensor.setBounds(100,this.PanelPrincipal.getHeight()-tamanyPis,30,50);
        creaPisos();
        pack();
    }
    
    /*
     * Timer que implementa es moviment de ascensor
     */
    Timer pujaPis = new Timer (TIMER_DELAY, new ActionListener () 
    {       
        @Override
        public void actionPerformed(ActionEvent ae) {
            if (ascensor.getLocation().y >= ((numPisos - (ascensor.getA()+1)) * tamanyPis)){
                ascensor.setLocation(100,ascensor.getLocation().y-1);
            }else{
                pujaPis.stop();
                ascensor.setA(ascensor.getA()+1);
            }
        }
    });
    
    Timer baixaPis = new Timer (TIMER_DELAY, new ActionListener () 
    {       
        @Override
        public void actionPerformed(ActionEvent ae) {
            if (ascensor.getLocation().y <= ((numPisos - (ascensor.getA()-1)) * tamanyPis)){
                ascensor.setLocation(100,ascensor.getLocation().y+1);
            }else{
                baixaPis.stop();
                ascensor.setA(ascensor.getA()-1);
            }
        }
    });
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Pujar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Baixar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelPrincipalLayout = new org.jdesktop.layout.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .add(PanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton2)))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelPrincipalLayout.createSequentialGroup()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    pujaPis.start();
}//GEN-LAST:event_jButton1MouseClicked

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    baixaPis.start();
}//GEN-LAST:event_jButton2MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Finestra().setVisible(true);
                
            }
        });
        
     
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
